package wizard

import (
	"fmt"
	"strings"
	"time"

	"github.com/DamianReeves/sync-tools/internal/rsync"
)

// ProgressMonitor manages real-time sync progress
type ProgressMonitor struct {
	info     *ProgressInfo
	runner   *rsync.Runner
	options  *rsync.Options
	active   bool
	complete bool
	failed   bool
	error    error
}

// NewProgressMonitor creates a new progress monitor
func NewProgressMonitor(state *ProgressState) *ProgressMonitor {
	return &ProgressMonitor{
		info: &state.Progress,
	}
}

// StartSync begins the sync operation
func (pm *ProgressMonitor) StartSync(state *ProgressState) error {
	// Convert wizard state to rsync options
	options, err := pm.convertWizardStateToRsyncOptions(state)
	if err != nil {
		return fmt.Errorf("failed to convert wizard state: %w", err)
	}

	pm.options = options
	pm.active = true
	pm.complete = false
	pm.failed = false
	pm.error = nil

	// Initialize progress info
	pm.info.CurrentFile = "Initializing..."
	pm.info.FilesProcessed = 0
	pm.info.TotalFiles = 0
	pm.info.TransferSpeed = "0 B/s"
	pm.info.ProgressPercent = 0
	pm.info.BytesTransferred = 0
	pm.info.TotalBytes = 0

	return nil
}

// IsActive returns true if sync is currently running
func (pm *ProgressMonitor) IsActive() bool {
	return pm.active && !pm.complete && !pm.failed
}

// IsComplete returns true if sync completed successfully
func (pm *ProgressMonitor) IsComplete() bool {
	return pm.complete
}

// IsFailed returns true if sync failed
func (pm *ProgressMonitor) IsFailed() bool {
	return pm.failed
}

// GetError returns the error if sync failed
func (pm *ProgressMonitor) GetError() error {
	return pm.error
}

// GetProgress returns current progress info
func (pm *ProgressMonitor) GetProgress() *ProgressInfo {
	return pm.info
}

// UpdateProgress updates progress information (called by sync engine)
func (pm *ProgressMonitor) UpdateProgress(current string, processed int, total int, speed string, percent int) {
	pm.info.CurrentFile = current
	pm.info.FilesProcessed = processed
	pm.info.TotalFiles = total
	pm.info.TransferSpeed = speed
	pm.info.ProgressPercent = percent
}

// CompleteSync marks the sync as completed
func (pm *ProgressMonitor) CompleteSync() {
	pm.active = false
	pm.complete = true
	pm.info.CurrentFile = "Sync completed successfully"
	pm.info.ProgressPercent = 100
}

// FailSync marks the sync as failed
func (pm *ProgressMonitor) FailSync(err error) {
	pm.active = false
	pm.failed = true
	pm.error = err
	pm.info.CurrentFile = "Sync failed"
}

// Cancel cancels the running sync operation
func (pm *ProgressMonitor) Cancel() error {
	if pm.active {
		pm.active = false
		pm.failed = true
		pm.error = fmt.Errorf("sync cancelled by user")
		pm.info.CurrentFile = "Sync cancelled"
	}
	return nil
}

// convertWizardStateToRsyncOptions converts wizard configuration to rsync options
func (pm *ProgressMonitor) convertWizardStateToRsyncOptions(state *ProgressState) (*rsync.Options, error) {
	options := &rsync.Options{
		Source: state.SourcePath,
		Dest:   state.DestinationPath,
		Mode:   state.SyncOptions.Mode,
		DryRun: state.SyncOptions.DryRun,
	}

	// Apply sync options
	if state.SyncOptions.HiddenDirs {
		options.ExcludeHiddenDirs = true
	}

	if state.SyncOptions.UseGitIgnore {
		options.UseSourceGitignore = true
	}

	// Add exclusion patterns
	for _, pattern := range state.Patterns {
		if pattern.Valid && pattern.Pattern != "" {
			options.IgnoreSrc = append(options.IgnoreSrc, pattern.Pattern)
		}
	}

	// Set conflict resolution strategy
	options.ConflictStrategy = state.SyncOptions.ConflictStrategy

	return options, nil
}

// GenerateSyncFile generates a SyncFile from the wizard configuration
func GenerateSyncFile(state *ProgressState) (string, error) {
	var content strings.Builder
	
	// Header comment
	content.WriteString("# Generated by sync-tools wizard\n")
	content.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().Format(time.RFC3339)))
	content.WriteString("\n")

	// Main SYNC instruction
	content.WriteString(fmt.Sprintf("SYNC %s %s\n", state.SourcePath, state.DestinationPath))

	// Mode configuration
	if state.SyncOptions.Mode != "one-way" {
		content.WriteString(fmt.Sprintf("MODE %s\n", state.SyncOptions.Mode))
	}

	// Dry run configuration
	if state.SyncOptions.DryRun {
		content.WriteString("DRYRUN true\n")
	}

	// Git ignore configuration
	if state.SyncOptions.UseGitIgnore {
		content.WriteString("GITIGNORE true\n")
	}

	// Hidden directories configuration
	if !state.SyncOptions.HiddenDirs {
		content.WriteString("HIDDEN_DIRS include\n")
	}

	// Exclusion patterns
	for _, pattern := range state.Patterns {
		if pattern.Valid && pattern.Pattern != "" && pattern.Source != "default" {
			content.WriteString(fmt.Sprintf("EXCLUDE %s\n", pattern.Pattern))
		}
	}

	// Conflict strategy
	if state.SyncOptions.ConflictStrategy != "newest-wins" {
		content.WriteString(fmt.Sprintf("CONFLICT_STRATEGY %s\n", state.SyncOptions.ConflictStrategy))
	}

	return content.String(), nil
}

// RenderProgressBar renders a text-based progress bar
func RenderProgressBar(percent int, width int) string {
	filled := int(float64(width) * float64(percent) / 100.0)
	empty := width - filled

	bar := strings.Repeat("█", filled) + strings.Repeat("░", empty)
	return fmt.Sprintf("[%s] %d%%", bar, percent)
}