Feature: Interactive Wizard
  As a DevOps engineer
  I want to use an interactive wizard to configure sync operations
  So that I can easily set up complex sync configurations with a guided interface

  Background:
    Given I have a source directory with nested files:
      | path                    | content           | size |
      | docs/README.md         | # Documentation   | 15B  |
      | src/main.go            | package main      | 12B  |
      | src/utils/helper.go    | package utils     | 13B  |
      | config/app.yml         | app_name: test    | 14B  |
      | .git/config            | [core]            | 6B   |
      | temp/cache.tmp         | cached data       | 11B  |
    And I have an empty destination directory

  Scenario: Wizard command is available
    When I run sync-tools with arguments "wizard --help"
    Then the command should succeed
    And the output should contain "Interactive wizard for sync configuration"

  Scenario: Wizard starts with source directory selection
    When I start the interactive wizard
    Then I should see the source directory selection screen
    And I should see "Select source directory"
    And I should see directory browser with navigation instructions

  Scenario: Directory tree browser shows file counts
    Given I start the interactive wizard
    When I navigate to the source directory selection
    Then the directory tree should show:
      | path        | files | size |
      | docs/       | 1     | 15B  |
      | src/        | 2     | 25B  |
      | config/     | 1     | 14B  |
      | .git/       | 1     | 6B   |
      | temp/       | 1     | 11B  |
    And I can navigate with arrow keys
    And I can select directories with Enter

  Scenario: Exclusion pattern management
    Given I start the interactive wizard
    And I have selected source and destination directories
    When I navigate to the exclusion patterns screen
    Then I should see current patterns:
      | pattern   | source    |
      | .git/     | default   |
    And I can add new patterns with "Add Pattern"
    And I can remove patterns with "Remove"
    And invalid patterns show validation errors

  Scenario: Progress screen shows real-time sync updates
    Given I start the interactive wizard
    And I have configured all sync options
    When I navigate to the progress screen
    And I start the sync operation
    Then I should see:
      | element           | value               |
      | current_file      | docs/README.md     |
      | files_processed   | 1                  |
      | total_files       | 6                  |
      | transfer_speed    | 1.2 KB/s           |
      | progress_percent  | 17%                |
    And the progress bar should update in real-time
    And I can cancel with Ctrl+C

  Scenario: Directory filter selection with statistics
    Given I start the interactive wizard
    And I have selected source and destination directories  
    When I navigate to the directory filter screen
    Then I should see directory list:
      | directory | files | size | selected |
      | docs/     | 1     | 15B  | true     |
      | src/      | 2     | 25B  | true     |
      | config/   | 1     | 14B  | true     |
      | .git/     | 1     | 6B   | false    |
      | temp/     | 1     | 11B  | true     |
    And I can toggle selection with Space
    And I can see totals: "Selected: 4 directories, 5 files, 54B"

  Scenario: Sync options configuration with interactive controls
    Given I start the interactive wizard
    When I navigate to the sync options screen
    Then I should see configurable options:
      | option              | type      | value     |
      | Mode                | radio     | one-way   |
      | Dry Run             | checkbox  | false     |
      | Hidden Directories  | checkbox  | true      |
      | Use Git Ignore      | checkbox  | false     |
      | Conflict Strategy   | select    | newest    |
    And I can navigate between options with Tab
    And I can toggle checkboxes with Space
    And I can change values with arrow keys

  Scenario: Complete wizard flow generates SyncFile
    Given I start the interactive wizard
    And I select source directory "./test_source"
    And I select destination directory "./test_dest"  
    And I configure sync mode as "two-way"
    And I add exclusion pattern "*.tmp"
    And I enable "Use Git Ignore"
    When I complete the wizard
    Then a SyncFile should be generated with:
      """
      # Generated by sync-tools wizard
      SYNC ./test_source ./test_dest
      MODE two-way
      EXCLUDE *.tmp
      GITIGNORE true
      """
    And the wizard should ask "Execute now?" with options [Yes] [Save Only] [Cancel]

  Scenario: Wizard preserves state when navigating back
    Given I start the interactive wizard
    And I select source directory "./test_source"
    And I select destination directory "./test_dest"
    And I configure sync mode as "two-way"
    When I navigate back to the source selection
    And I navigate forward to sync options
    Then the sync mode should still be "two-way"
    And all previously configured options should be preserved

  Scenario: Wizard handles errors gracefully  
    Given I start the interactive wizard
    When I select a non-existent source directory "/nonexistent/path"
    Then I should see error message "Directory does not exist: /nonexistent/path"
    And I should remain on the source selection screen
    And I should be able to select a different directory

  Scenario: Wizard supports pre-filled options from command line
    When I run sync-tools with arguments "wizard --test --source ./test_source --mode two-way"
    Then the wizard should start with source directory pre-selected as "./test_source"
    And the sync mode should be pre-configured as "two-way"
    And I should be able to proceed to destination selection