name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y rsync
      - name: Create virtualenv and install deps
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -e .
      - name: Run tests
        run: |
          source .venv/bin/activate
          make test

  integration:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Create virtualenv and install deps
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -e .
      - name: Run integration tests
        run: |
          source .venv/bin/activate
          .venv/bin/pytest -q tests/test_integration.py tests/test_report.py
